spring:
  application:
    name: ai-code-generator-backend  # 这个是你这个 application 的名称 不是要你去对应你目录的名称 就比如一个大项目下的不同模块的名称

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: me.cmx.aicodegenerator.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


